sudo: false
language: python

python: 3.5

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35

matrix:
  include:
  - python: 3.6
    env:
    - TOX_ENV=py36

install:
  - pip install flake8 tox

script:
  - flake8 papyrus
  - tox -e $TOX_ENV --sitepackages -- -v --cover-package papyrus
